# Generated by Django 3.2.9 on 2021-12-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='control_status',
        ),
        migrations.AddField(
            model_name='moment',
            name='if_status',
            field=models.SmallIntegerField(choices=[(0, '显示'), (1, '条件隐身')], default=0, verbose_name='显示状态'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='moment_status',
            field=models.SmallIntegerField(choices=[(0, '个人可见'), (1, '广场可见')], default=0, verbose_name='控制状态'),
        ),
    ]
