# Generated by Django 3.2.9 on 2021-12-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211201_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='moment',
            name='name',
        ),
    ]
