# Generated by Django 3.2.9 on 2021-12-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211201_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='topic',
        ),
        migrations.AlterField(
            model_name='moment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_moment', to='api.userinfo', verbose_name='用户'),
        ),
    ]
