# Generated by Django 3.2.9 on 2021-12-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211201_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentrecord',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='commentrecord',
            name='name',
        ),
        migrations.AlterField(
            model_name='moment',
            name='moment_status',
            field=models.SmallIntegerField(choices=[(0, '广场可见'), (1, '主页可见')], default=0, verbose_name='控制状态'),
        ),
    ]
