# Generated by Django 3.2.9 on 2021-12-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211202_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrecord',
            name='avatarUrl',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='随机头像'),
        ),
        migrations.AddField(
            model_name='commentrecord',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='随机名字'),
        ),
    ]
