# Generated by Django 3.2.9 on 2021-12-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211202_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentrecord',
            old_name='nickname',
            new_name='nickName',
        ),
    ]
