# Generated by Django 3.2.9 on 2021-12-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_nickname_commentrecord_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='moment_status',
            field=models.SmallIntegerField(choices=[(0, '广场可见'), (1, '主页可见'), (2, '个人可见')], default=0, verbose_name='控制状态'),
        ),
    ]
