# Generated by Django 3.2.9 on 2021-12-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_moment_moment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='focus_count',
            field=models.PositiveIntegerField(default=0, verbose_name='关注次数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='focused_count',
            field=models.PositiveIntegerField(default=0, verbose_name='被关注次数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='viewer_count',
            field=models.PositiveIntegerField(default=0, verbose_name='被看次数'),
        ),
    ]
