# Generated by Django 3.2.9 on 2021-12-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211203_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentrecord',
            old_name='comment_status',
            new_name='if_status',
        ),
    ]
