# Generated by Django 3.2.9 on 2021-12-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_comment_status_commentrecord_if_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentrecord',
            old_name='if_status',
            new_name='comment_status',
        ),
    ]
