# Generated by Django 3.2.9 on 2021-12-03 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_if_status_commentrecord_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrecord',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='api.commentrecord', verbose_name='回复评论ID'),
        ),
        migrations.AlterField(
            model_name='commentrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='评论用户'),
        ),
    ]
