# Generated by Django 3.2.9 on 2021-12-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211204_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacitTestDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='题目')),
                ('answer1', models.CharField(max_length=255, verbose_name='回答1')),
                ('answer2', models.CharField(blank=True, max_length=255, null=True, verbose_name='回答1')),
                ('answer3', models.CharField(blank=True, max_length=255, null=True, verbose_name='回答1')),
                ('answer4', models.CharField(blank=True, max_length=255, null=True, verbose_name='回答1')),
                ('answer5', models.CharField(blank=True, max_length=255, null=True, verbose_name='回答1')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
            ],
            options={
                'verbose_name': '默契测试',
                'verbose_name_plural': '默契测试',
                'db_table': 'tacit_test',
            },
        ),
    ]
