# Generated by Django 3.2.9 on 2021-12-07 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tacittestdatabase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tacittestdatabase',
            name='used_count',
        ),
        migrations.RemoveField(
            model_name='topiccitedrecord',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='topiccitedrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='tacittestdatabase',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='默契测试创建日期'),
        ),
        migrations.CreateModel(
            name='TacitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='评论次数')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='使用日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='好友测试创建者')),
            ],
            options={
                'verbose_name': '默契记录',
                'verbose_name_plural': '默契记录',
                'db_table': 'tacit_record',
            },
        ),
        migrations.CreateModel(
            name='TacitCitedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tacitRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tacitrecord', verbose_name='默契测试记录')),
                ('tacitTestDatabase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tacittestdatabase', verbose_name='默契测试题库')),
            ],
            options={
                'verbose_name': '默契引用记录',
                'verbose_name_plural': '默契引用记录',
                'db_table': 'tacit_cited_record',
            },
        ),
    ]
