# Generated by Django 3.2.9 on 2021-12-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211207_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacittestdatabase',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='默契测试创建日期'),
        ),
    ]
