# Generated by Django 3.2.9 on 2021-12-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_tacittestdatabase_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacitcitedrecord',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='创建者设定的答案'),
        ),
        migrations.AddField(
            model_name='tacitrecord',
            name='bonus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='奖励'),
        ),
        migrations.AddField(
            model_name='tacitrecord',
            name='correct_count',
            field=models.PositiveIntegerField(default=0, verbose_name='给定答对可获得奖励的数量'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='real_avatarUrl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='微信用户头像'),
        ),
        migrations.AlterField(
            model_name='tacittestdatabase',
            name='answer2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回答2'),
        ),
        migrations.AlterField(
            model_name='tacittestdatabase',
            name='answer3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回答3'),
        ),
        migrations.AlterField(
            model_name='tacittestdatabase',
            name='answer4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回答4'),
        ),
        migrations.AlterField(
            model_name='tacittestdatabase',
            name='answer5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回答5'),
        ),
    ]
