# Generated by Django 3.2.9 on 2021-12-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_userinfo_real_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacitrecord',
            name='avatarUrlFlag',
            field=models.SmallIntegerField(choices=[(0, '随机头像'), (1, '微信头像')], default=0, verbose_name='头像类型'),
        ),
    ]
