# Generated by Django 3.2.9 on 2021-12-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_tacitrecord_avatarurlflag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tacitcitedrecord',
            old_name='correct_answer',
            new_name='selected_answer',
        ),
    ]
