# Generated by Django 3.2.9 on 2021-12-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_correct_answer_tacitcitedrecord_selected_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacittestdatabase',
            name='title',
            field=models.CharField(max_length=255, verbose_name='题目'),
        ),
    ]
