# Generated by Django 3.2.9 on 2021-12-11 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_tacitrecord_tacit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacitReplyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatarUrlFlag', models.SmallIntegerField(choices=[(0, '随机头像'), (1, '微信头像')], default=0, verbose_name='头像类型')),
                ('if_status', models.SmallIntegerField(choices=[(0, '显示'), (1, '条件隐身')], default=0, verbose_name='条件隐身状态')),
                ('favor_count', models.PositiveIntegerField(default=0, verbose_name='被点赞次数')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='使用日期')),
                ('tacitRecord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tacitrecord', verbose_name='默契测试')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='默契测试回复者')),
            ],
            options={
                'verbose_name': '默契回复记录',
                'verbose_name_plural': '默契回复记录',
                'db_table': 'tacit_reply_record',
            },
        ),
        migrations.CreateModel(
            name='TacitReplyCitedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='回复的答案')),
                ('tacitReplyRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tacitrecord', verbose_name='默契测试记录')),
                ('tacitTestDatabase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tacittestdatabase', verbose_name='默契测试题库')),
            ],
            options={
                'verbose_name': '默契回复引用记录',
                'verbose_name_plural': '默契回复引用记录',
                'db_table': 'tacit_reply_cited_record',
            },
        ),
    ]
