# Generated by Django 3.2.9 on 2021-12-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_tacitreplycitedrecord_tacitreplyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacitreplyrecord',
            name='bonus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='奖励'),
        ),
    ]
