# Generated by Django 3.2.9 on 2021-12-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_tacitreplyrecord_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacitreplyrecord',
            name='match_count',
            field=models.PositiveIntegerField(default=0, verbose_name='匹配数'),
        ),
    ]
