# Generated by Django 3.2.9 on 2021-12-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_tacitreplyrecord_match_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacitreplycitedrecord',
            name='tacitReplyRecord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tacitreplyrecord', verbose_name='默契测试记录'),
        ),
    ]
