# Generated by Django 3.2.9 on 2021-12-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_tacitreplycitedrecord_tacitreplyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacitreplyrecord',
            name='selected_answer_q1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回复的答案1'),
        ),
        migrations.AddField(
            model_name='tacitreplyrecord',
            name='selected_answer_q10',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回复的答案10'),
        ),
        migrations.AddField(
            model_name='tacitreplyrecord',
            name='selected_answer_q2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回复的答案2'),
        ),
        migrations.AddField(
            model_name='tacitreplyrecord',
            name='selected_answer_q3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回复的答案3'),
        ),
        migrations.AddField(
            model_name='tacitreplyrecord',
            name='selected_answer_q4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回复的答案4'),
        ),
        migrations.AddField(
            model_name='tacitreplyrecord',
            name='selected_answer_q5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回复的答案5'),
        ),
        migrations.AddField(
            model_name='tacitreplyrecord',
            name='selected_answer_q6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回复的答案6'),
        ),
        migrations.AddField(
            model_name='tacitreplyrecord',
            name='selected_answer_q7',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回复的答案7'),
        ),
        migrations.AddField(
            model_name='tacitreplyrecord',
            name='selected_answer_q8',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回复的答案8'),
        ),
        migrations.AddField(
            model_name='tacitreplyrecord',
            name='selected_answer_q9',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回复的答案9'),
        ),
        migrations.AlterField(
            model_name='tacitrecord',
            name='bonus',
            field=models.SmallIntegerField(choices=[(0, '无'), (1, '随机')], default=0, verbose_name='奖励'),
        ),
        migrations.DeleteModel(
            name='TacitReplyCitedRecord',
        ),
    ]
