# Generated by Django 3.2.9 on 2021-12-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20211212_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacitreplyrecord',
            name='tacitReply_status',
            field=models.SmallIntegerField(choices=[(0, '广场可见'), (1, '主页可见'), (2, '个人可见')], default=0, verbose_name='控制状态'),
        ),
    ]
