# Generated by Django 3.2.9 on 2021-12-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_tacitreplyrecord_tacitreply_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tacitreplyrecord',
            name='tacitReply_status',
        ),
    ]
