# Generated by Django 3.2.9 on 2021-12-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_tacitreplyrecord_tacitreply_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tacitreplyrecord',
            name='selected_answer_q1',
        ),
        migrations.RemoveField(
            model_name='tacitreplyrecord',
            name='selected_answer_q10',
        ),
        migrations.RemoveField(
            model_name='tacitreplyrecord',
            name='selected_answer_q2',
        ),
        migrations.RemoveField(
            model_name='tacitreplyrecord',
            name='selected_answer_q3',
        ),
        migrations.RemoveField(
            model_name='tacitreplyrecord',
            name='selected_answer_q4',
        ),
        migrations.RemoveField(
            model_name='tacitreplyrecord',
            name='selected_answer_q5',
        ),
        migrations.RemoveField(
            model_name='tacitreplyrecord',
            name='selected_answer_q6',
        ),
        migrations.RemoveField(
            model_name='tacitreplyrecord',
            name='selected_answer_q7',
        ),
        migrations.RemoveField(
            model_name='tacitreplyrecord',
            name='selected_answer_q8',
        ),
        migrations.RemoveField(
            model_name='tacitreplyrecord',
            name='selected_answer_q9',
        ),
        migrations.CreateModel(
            name='TacitReplyCitedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='回复设定的答案')),
                ('tacitReplyRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tacitreplyrecord', verbose_name='回复默契测试记录')),
            ],
            options={
                'verbose_name': '回复默契引用记录',
                'verbose_name_plural': '回复默契引用记录',
                'db_table': 'tacit_reply_cited_record',
            },
        ),
    ]
