# Generated by Django 3.2.9 on 2021-12-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_tacitrecord_tacit_reply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacitreplyrecord',
            name='tacitRecord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tacitrecord', verbose_name='默契测试'),
        ),
    ]
