# Generated by Django 3.2.9 on 2021-12-16 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_tacitreplyrecord_tacitrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='瞬间发布日期'),
        ),
    ]
