# Generated by Django 3.2.9 on 2021-12-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_moment_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentviewerrecord',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AddField(
            model_name='topicviewerrecord',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AddField(
            model_name='userviewerrecord',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='瞬间发布日期'),
        ),
    ]
