# Generated by Django 3.2.9 on 2021-12-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20211216_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='momentviewerrecord',
            old_name='view_count',
            new_name='viewer_count',
        ),
        migrations.RenameField(
            model_name='topicviewerrecord',
            old_name='view_count',
            new_name='viewer_count',
        ),
        migrations.RenameField(
            model_name='userviewerrecord',
            old_name='view_count',
            new_name='viewer_count',
        ),
    ]
