# Generated by Django 3.2.9 on 2021-12-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20211216_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentviewerrecord',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最近浏览日期'),
        ),
    ]
