# Generated by Django 3.2.9 on 2021-12-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_momentviewerrecord_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userviewerrecord',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='用户浏览的时间'),
        ),
    ]
