# Generated by Django 3.2.9 on 2021-12-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_userviewerrecord_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userviewerrecord',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userviewerrecord',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='用户浏览的时间'),
        ),
    ]
