# Generated by Django 3.2.9 on 2021-12-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_userviewerrecord_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userviewerrecord',
            name='create_time',
            field=models.DateTimeField(blank=True, verbose_name='用户浏览的时间'),
        ),
    ]
