# Generated by Django 3.2.9 on 2021-12-16 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_userviewerrecord_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userviewerrecord',
            name='is_active',
        ),
    ]
