# Generated by Django 3.2.9 on 2021-12-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_userviewerrecord_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userviewerrecord',
            name='create_time',
            field=models.DateTimeField(verbose_name='用户浏览的时间'),
        ),
    ]
