# Generated by Django 3.2.9 on 2021-12-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_userviewerrecord_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userviewerrecord',
            old_name='create_time',
            new_name='create_date',
        ),
    ]
