# Generated by Django 3.2.9 on 2021-12-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_rename_create_time_userviewerrecord_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userviewerrecord',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='用户浏览的时间'),
        ),
    ]
