# Generated by Django 3.2.9 on 2021-12-16 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_userviewerrecord_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userviewerrecord',
            old_name='create_date',
            new_name='create_time',
        ),
    ]
