# Generated by Django 3.2.9 on 2021-12-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_rename_create_date_userviewerrecord_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='momentviewerrecord',
            old_name='create_date',
            new_name='create_time',
        ),
    ]
