# Generated by Django 3.2.9 on 2021-12-17 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20211217_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='viewer_count_page3',
            field=models.PositiveIntegerField(default=0, verbose_name='朋友眼中的我被看次数'),
        ),
        migrations.CreateModel(
            name='UserViewerRecordPage3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='用户浏览的时间')),
                ('viewer_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_viewer_page3', to='api.userinfo', verbose_name='被浏览的用户')),
                ('viewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewer_user_viewer_page3', to='api.userinfo', verbose_name='浏览的用户')),
            ],
            options={
                'verbose_name': '朋友眼中的我浏览记录',
                'verbose_name_plural': '朋友眼中的我浏览记录',
                'db_table': 'user_viewer_record_page3',
            },
        ),
    ]
