# Generated by Django 3.2.9 on 2021-12-17 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20211217_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacitReplyWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='用户浏览的时间')),
                ('viewer_count', models.PositiveIntegerField(default=0, verbose_name='填写次数')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tacit_reply_write', to='api.userinfo', verbose_name='被浏览的用户')),
                ('viewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewer_tacit_reply_write', to='api.userinfo', verbose_name='浏览的用户')),
            ],
            options={
                'verbose_name': '好友默契回复填写完成记录',
                'verbose_name_plural': '好友默契回复填写完成记录',
                'db_table': 'tacit_reply_write',
            },
        ),
        migrations.CreateModel(
            name='TacitReplyViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='用户浏览的时间')),
                ('viewer_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tacit_reply_viewer', to='api.userinfo', verbose_name='被浏览的用户')),
                ('viewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewer_tacit_reply_viewer', to='api.userinfo', verbose_name='浏览的用户')),
            ],
            options={
                'verbose_name': '好友默契回复点击记录',
                'verbose_name_plural': '好友默契回复点击记录',
                'db_table': 'tacit_reply_viewer',
            },
        ),
    ]
