# Generated by Django 3.2.9 on 2021-12-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_tacitreplyviewer_tacitreplywrite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='tacit_viewer_count',
            field=models.PositiveIntegerField(default=0, verbose_name='好友测试扫码次数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tacit_write_count',
            field=models.PositiveIntegerField(default=0, verbose_name='好友测试填写次数'),
        ),
    ]
