# Generated by Django 3.2.9 on 2021-12-17 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_rename_viewer_count_tacitreplywrite_write_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TacitReplyViewer',
        ),
    ]
