# Generated by Django 3.2.9 on 2021-12-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20211219_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='momentviewerrecord',
            old_name='user',
            new_name='viewer_user',
        ),
    ]
