# Generated by Django 3.2.9 on 2021-12-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_rename_user_momentviewerrecord_viewer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '女'), (1, '男')], default=0, verbose_name='性别'),
        ),
    ]
