# Generated by Django 3.2.9 on 2021-12-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_userinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='Latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='moment',
            name='Longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='moment',
            name='addressName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='瞬间发布的位置名称'),
        ),
    ]
