# Generated by Django 3.2.9 on 2021-12-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20211225_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moment',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='moment',
            old_name='Longitude',
            new_name='longitude',
        ),
    ]
